In [1]:
import cbrkit
import pandas as pd
import numpy as np
import polars as pl

In [2]:
file_path ='/Users/macbookair/Documents/UFSM/COM804/diabetes_cleaned.csv'

In [3]:
## read the dataset
df = pd.read_csv('/Users/macbookair/Documents/UFSM/COM804/diabetes_cleaned.csv')
#print top 5 rows
df.head()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N

In [4]:
df.describe()

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI
count,800.0000,8.000000e+02,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000
mean,400.5000,3.237742e+05,53.880000,5.064554,67.558750,8.499325,4.955900,2.331387,1.224563,2.621050,1.934750,29.923062
std,231.0844,3.777967e+06,8.364542,2.892686,57.591015,2.468488,1.311315,1.397187,0.706753,1.167342,3.930872,4.877135
min,1.0000,1.230000e+02,20.000000,0.500000,20.000000,0.900000,0.600000,0.300000,0.200000,0.300000,0.100000,19.000000
25%,200.7500,2.408775e+04,51.000000,3.600000,47.000000,6.800000,4.100000,1.500000,0.900000,1.700000,0.700000,26.000000
50%,400.5000,3.441250e+04,55.000000,4.500000,59.000000,8.200000,4.800000,2.000000,1.100000,2.500000,1.000000,30.000000
75%,600.2500,4.538850e+04,59.000000,5.700000,73.000000,10.200000,5.700000,2.900000,1.350000,3.300000,1.500000,33.000000
max,800.0000,7.543566e+07,79.000000,38.900000,800.000000,16.000000,10.300000,13.800000,9.900000,9.900000,35.000000,47.750000

In [5]:
df.columns

Index(['ID', 'No_Pation', 'Gender', 'AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG',
       'HDL', 'LDL', 'VLDL', 'BMI', 'CLASS'],
      dtype='object')

In [6]:
## Build and extract the row to use for the test
ID_col = "ID"
target_col = "CLASS"

#for reproducibilility
np.random.seed(42)

## convert the ID to a list
# all_id = df.select("ID").to_series().to_list()
all_id = df["ID"].to_list()
test_id = np.random.choice(all_id)
print(f"The random ID chosen is {test_id}")

The random ID chosen is 505

In [31]:
# extract the random row
test_data = df[df['ID'] ==  test_id]
#view the full row of the test data
test_data

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
102,505,23044,F,48,4.0,38,6.5,4.4,2.3,1.3,2.2,1.0,23.0,Y

In [32]:
## drop the class column of the test data
test_data = test_data.drop(['CLASS', 'ID', 'No_Pation'], axis=1)
test_data

    Gender  AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL   BMI
102      F   48   4.0  38    6.5   4.4  2.3  1.3  2.2   1.0  23.0

In [10]:
data = df[df["ID"] != test_id]
print(data.shape)

(799, 14)

In [32]:
# Buid the similiarity search
new_data.describe()

shape: (9, 15)
┌────────────┬────────────┬───────────────┬────────┬───┬──────────┬──────────┬───────────┬───────┐
│ statistic  ┆ ID         ┆ No_Pation     ┆ Gender ┆ … ┆ LDL      ┆ VLDL     ┆ BMI       ┆ CLASS │
│ ---        ┆ ---        ┆ ---           ┆ ---    ┆   ┆ ---      ┆ ---      ┆ ---       ┆ ---   │
│ str        ┆ f64        ┆ f64           ┆ str    ┆   ┆ f64      ┆ f64      ┆ f64       ┆ str   │
╞════════════╪════════════╪═══════════════╪════════╪═══╪══════════╪══════════╪═══════════╪═══════╡
│ count      ┆ 799.0      ┆ 799.0         ┆ 799    ┆ … ┆ 799.0    ┆ 799.0    ┆ 799.0     ┆ 799   │
│ null_count ┆ 0.0        ┆ 0.0           ┆ 0      ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0       ┆ 0     │
│ mean       ┆ 400.369212 ┆ 324150.625782 ┆ null   ┆ … ┆ 2.621577 ┆ 1.93592  ┆ 29.931727 ┆ null  │
│ std        ┆ 231.199515 ┆ 3.7803e6      ┆ null   ┆ … ┆ 1.167978 ┆ 3.933195 ┆ 4.874025  ┆ null  │
│ min        ┆ 1.0        ┆ 123.0         ┆ F      ┆ … ┆ 0.3      ┆ 0.1      ┆ 19.0      ┆ N     │
│ 25%        ┆ 201.0      ┆ 24089.0       ┆ null   ┆ … ┆ 1.7      ┆ 0.7      ┆ 26.0      ┆ null  │
│ 50%        ┆ 400.0      ┆ 34413.0       ┆ null   ┆ … ┆ 2.5      ┆ 1.0      ┆ 30.0      ┆ null  │
│ 75%        ┆ 601.0      ┆ 45393.0       ┆ null   ┆ … ┆ 3.3      ┆ 1.5      ┆ 33.0      ┆ null  │
│ max        ┆ 800.0      ┆ 7.5435657e7   ┆ f      ┆ … ┆ 9.9      ┆ 35.0     ┆ 47.75     ┆ Y     │
└────────────┴────────────┴───────────────┴────────┴───┴──────────┴──────────┴───────────┴───────┘

In [12]:
# Extract the numeric columns and drop the ID, No_Pation and AGE columns
cols = data.select_dtypes(include=["number"]).columns.drop(['ID', 'No_Pation', 'AGE'])
print(cols)

Index(['Urea', 'Cr', 'HbA1c', 'Chol', 'TG', 'HDL', 'LDL', 'VLDL', 'BMI'], dtype='object')

In [13]:
## View the statistics of the dataset
data.describe()

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI
count,799.000000,7.990000e+02,799.000000,799.000000,799.000000,799.000000,799.000000,799.000000,799.000000,799.000000,799.000000,799.000000
mean,400.369212,3.241506e+05,53.887359,5.065886,67.595745,8.501827,4.956596,2.331427,1.224468,2.621577,1.935920,29.931727
std,231.199515,3.780319e+06,8.367189,2.894252,57.617575,2.469018,1.311989,1.398062,0.707190,1.167978,3.933195,4.874025
min,1.000000,1.230000e+02,20.000000,0.500000,20.000000,0.900000,0.600000,0.300000,0.200000,0.300000,0.100000,19.000000
25%,200.500000,2.408850e+04,51.000000,3.600000,47.000000,6.800000,4.100000,1.500000,0.900000,1.700000,0.700000,26.000000
50%,400.000000,3.441300e+04,55.000000,4.500000,59.000000,8.200000,4.800000,2.000000,1.100000,2.500000,1.000000,30.000000
75%,600.500000,4.539000e+04,59.000000,5.700000,73.000000,10.200000,5.700000,2.900000,1.350000,3.300000,1.500000,33.000000
max,800.000000,7.543566e+07,79.000000,38.900000,800.000000,16.000000,10.300000,13.800000,9.900000,9.900000,35.000000,47.750000

There are huge outliers in attributes like Cr, VLDL and a litle in the rest. so we need to clean the outliers

In [ ]:
## remove outliers 
Q3 = data[cols].quantile(0.75)
Q1 = data[cols].quantile(0.25)
IQR = Q3 - Q1
hi = Q3 + 1.5 * IQR
lo = Q1 - 1.5 * IQR 

#filters he dataset to find ehre the columns that has a lower or higher value than the IQR
outlier_mask = (data[cols] < lo) | (data[cols] > hi)
##selects rows that has outliers
data_outliers = data[outlier_mask.any(axis=1)]
##drops rows that has outliers and reset the index
data_clean = data.loc[~outlier_mask.any(axis=1)].copy().reset_index(drop=True)

In [87]:
data_clean.describe()

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI
count,606.000000,6.060000e+02,606.000000,606.000000,606.000000,606.000000,606.000000,606.000000,606.000000,606.000000,606.000000,606.000000
mean,389.933993,8.816307e+04,53.764026,4.493894,57.894389,8.434752,4.858911,2.126238,1.118861,2.614917,0.994884,29.462706
std,229.020225,5.128972e+05,8.339021,1.469507,17.351173,2.482039,1.130981,1.006190,0.321788,1.028667,0.467231,4.689324
min,2.000000,1.230000e+02,20.000000,0.500000,20.000000,3.700000,2.000000,0.300000,0.400000,0.750000,0.100000,19.000000
25%,201.250000,2.408250e+04,51.000000,3.400000,45.000000,6.800000,4.100000,1.400000,0.900000,1.800000,0.700000,26.000000
50%,386.500000,3.439100e+04,55.000000,4.400000,56.000000,8.200000,4.900000,2.000000,1.100000,2.500000,0.900000,30.000000
75%,569.750000,4.352400e+04,59.000000,5.400000,70.000000,10.200000,5.600000,2.700000,1.300000,3.400000,1.300000,33.000000
max,800.000000,8.785782e+06,79.000000,8.800000,106.000000,15.000000,8.100000,5.000000,2.000000,5.600000,2.600000,39.000000

In [88]:
data_clean.shape

(606, 14)

In [89]:
# convert the cleaned dataframe from Pandas DF to Polars DF
new_data = pl.from_pandas(data_clean)

In [90]:
## load the data into a casebase
casebase = cbrkit.loaders.polars(new_data)
casebase

polars(df=shape: (606, 14)
┌─────┬───────────┬────────┬─────┬───┬─────┬──────┬──────┬───────┐
│ ID  ┆ No_Pation ┆ Gender ┆ AGE ┆ … ┆ LDL ┆ VLDL ┆ BMI  ┆ CLASS │
│ --- ┆ ---       ┆ ---    ┆ --- ┆   ┆ --- ┆ ---  ┆ ---  ┆ ---   │
│ i64 ┆ i64       ┆ str    ┆ i64 ┆   ┆ f64 ┆ f64  ┆ f64  ┆ str   │
╞═════╪═══════════╪════════╪═════╪═══╪═════╪══════╪══════╪═══════╡
│ 735 ┆ 34221     ┆ M      ┆ 26  ┆ … ┆ 2.1 ┆ 0.6  ┆ 23.0 ┆ N     │
│ 504 ┆ 34223     ┆ M      ┆ 33  ┆ … ┆ 2.0 ┆ 0.4  ┆ 21.0 ┆ N     │
│ 634 ┆ 34224     ┆ F      ┆ 45  ┆ … ┆ 1.5 ┆ 0.4  ┆ 21.0 ┆ N     │
│ 721 ┆ 34225     ┆ F      ┆ 50  ┆ … ┆ 2.1 ┆ 0.6  ┆ 24.0 ┆ N     │
│ 421 ┆ 34227     ┆ M      ┆ 48  ┆ … ┆ 1.6 ┆ 0.4  ┆ 24.0 ┆ N     │
│ …   ┆ …         ┆ …      ┆ …   ┆ … ┆ …   ┆ …    ┆ …    ┆ …     │
│ 194 ┆ 454316    ┆ F      ┆ 57  ┆ … ┆ 1.4 ┆ 1.3  ┆ 29.0 ┆ Y     │
│ 195 ┆ 4543      ┆ f      ┆ 55  ┆ … ┆ 3.1 ┆ 0.7  ┆ 33.0 ┆ Y     │
│ 196 ┆ 454316    ┆ M      ┆ 55  ┆ … ┆ 2.9 ┆ 0.7  ┆ 27.0 ┆ Y     │
│ 198 ┆ 454316    ┆ M      ┆ 28  ┆ … ┆ 2.6 ┆ 0.8  ┆ 37.0 ┆ Y     │
│ 248 ┆ 24054     ┆ M      ┆ 54  ┆ … ┆ 3.0 ┆ 0.7  ┆ 33.0 ┆ Y     │
└─────┴───────────┴────────┴─────┴───┴─────┴──────┴──────┴───────┘)

In [91]:
# test_data = test_data.drop(columns=['ID', 'No_Pation'], axis=1)

In [92]:
## Create a test data for data retrieval 
new_test_data = data_clean[data_clean['ID'] == 248]

#Drop the ID, No_Pation and CLASS columns
new_test_data = new_test_data.drop(columns = ['ID', 'No_Pation', 'CLASS'])

#convert the new test data to polar df
new_test_query = pl.from_pandas(new_test_data)
new_query = new_test_query.to_dicts()[0]
new_query

{'Gender': 'M',
 'AGE': 54,
 'Urea': 5.0,
 'Cr': 67,
 'HbA1c': 6.9,
 'Chol': 3.8,
 'TG': 1.7,
 'HDL': 1.1,
 'LDL': 3.0,
 'VLDL': 0.7,
 'BMI': 33.0}

In [93]:
## Define Query

#convert test data to query
test_query = pl.from_pandas(test_data)
# queries = cbrkit.loaders.polars(test_query)
query = test_query.to_dicts()[0]
query

{'Gender': 'F',
 'AGE': 48,
 'Urea': 4.0,
 'Cr': 38,
 'HbA1c': 6.5,
 'Chol': 4.4,
 'TG': 2.3,
 'HDL': 1.3,
 'LDL': 2.2,
 'VLDL': 1.0,
 'BMI': 23.0}

In [143]:
# # extracting the data as query
# query = cbrkit.helpers.singleton(queries)
# query

In [34]:
new_data.columns

['ID',
 'No_Pation',
 'Gender',
 'AGE',
 'Urea',
 'Cr',
 'HbA1c',
 'Chol',
 'TG',
 'HDL',
 'LDL',
 'VLDL',
 'BMI',
 'CLASS']

In [84]:
# #### Create similiarity search

# mac_sim = cbrkit.sim.attribute_value(
#     attributes = {
#         "Gender": cbrkit.sim.generic.equality(),
#     }
# )

# fac_sim = cbrkit.sim.attribute_value(
#     attributes= {
#         "AGE":  cbrkit.sim.numbers.linear(max_distance= 20),
#         "Urea": cbrkit.sim.numbers.linear(max_distance= 1.5),
#         "Cr":   cbrkit.sim.numbers.linear(max_distance= 17.5),
#         "HbA1c":cbrkit.sim.numbers.linear(max_distance= 2.5),
#         "Chol": cbrkit.sim.numbers.linear(max_distance= 1.5),
#         "TG":   cbrkit.sim.numbers.linear(max_distance= 1.0),
#         "HDL":  cbrkit.sim.numbers.linear(max_distance=0.33),
#         "LDL":  cbrkit.sim.numbers.linear(max_distance=1.05),
#         "VLDL": cbrkit.sim.numbers.linear(max_distance=0.5),
#         "BMI":  cbrkit.sim.numbers.linear(max_distance= 5)
#     }
# )


# mac_retriever = cbrkit.retrieval.build(mac_sim, minimum_similiarity=1.0)
# fac_retriever = cbrkit.retrieval.build(fac_sim, limit=10)

# result = cbrkit.retrieval.apply(casebase, query, [mac_retriever, fac_retriever])

In [ ]:
#### Create similiarity search

mac_sim = cbrkit.sim.attribute_value(
    attributes = {
        'Gender' : cbrkit.sim.generic.equality()
    }
)

fac_sim = cbrkit.sim.attribute_value(
    attributes= {
        "AGE":  cbrkit.sim.numbers.linear(max=20),
        "Urea": cbrkit.sim.numbers.linear(max=1.5),
        "Cr":   cbrkit.sim.numbers.linear(max=17.5),
        "HbA1c":cbrkit.sim.numbers.linear(max=2.5),
        "Chol": cbrkit.sim.numbers.linear(max=1.5),
        "TG":   cbrkit.sim.numbers.linear(max=1.0),
        "HDL":  cbrkit.sim.numbers.linear(max=0.33),
        "LDL":  cbrkit.sim.numbers.linear(max=1.05),
        "VLDL": cbrkit.sim.numbers.linear(max=0.5),
        "BMI":  cbrkit.sim.numbers.linear(max=5)
    }
)

In [94]:
# Retrieval function to select the top 100 cases where there is an exact similiarity of the same gender  
mac_retriever = cbrkit.retrieval.dropout(cbrkit.retrieval.build(mac_sim),
                                         min_similarity = 1.0,
                                         limit = 300)

##  Function to select the top 10 similar case to the query
fac_retriver = cbrkit.retrieval.dropout(cbrkit.retrieval.build(fac_sim), 
                                        limit=10)

## Apply the retrieval functions to the casebase and the query
result = cbrkit.retrieval.apply_query(casebase, query, (mac_retriever, fac_retriver))

In [95]:
## view the top 10 similar cases 
result.final_step.similarities

{97: AttributeValueSim(value=0.948, attributes={'AGE': 1.0, 'Urea': 1.0, 'Cr': 1.0, 'HbA1c': 0.8800000000000001, 'Chol': 1.0, 'TG': 1.0, 'HDL': 1.0, 'LDL': 1.0, 'VLDL': 1.0, 'BMI': 0.6}),
 98: AttributeValueSim(value=0.948, attributes={'AGE': 1.0, 'Urea': 1.0, 'Cr': 1.0, 'HbA1c': 0.8800000000000001, 'Chol': 1.0, 'TG': 1.0, 'HDL': 1.0, 'LDL': 1.0, 'VLDL': 1.0, 'BMI': 0.6}),
 100: AttributeValueSim(value=0.948, attributes={'AGE': 1.0, 'Urea': 1.0, 'Cr': 1.0, 'HbA1c': 0.8800000000000001, 'Chol': 1.0, 'TG': 1.0, 'HDL': 1.0, 'LDL': 1.0, 'VLDL': 1.0, 'BMI': 0.6}),
 103: AttributeValueSim(value=0.948, attributes={'AGE': 1.0, 'Urea': 1.0, 'Cr': 1.0, 'HbA1c': 0.8800000000000001, 'Chol': 1.0, 'TG': 1.0, 'HDL': 1.0, 'LDL': 1.0, 'VLDL': 1.0, 'BMI': 0.6}),
 87: AttributeValueSim(value=0.6892380952380952, attributes={'AGE': 0.7, 'Urea': 0.19999999999999987, 'Cr': 0.9428571428571428, 'HbA1c': 0.23999999999999985, 'Chol': 0.8000000000000002, 'TG': 0.7999999999999998, 'HDL': 1.0, 'LDL': 0.8095238095238098, 'VLDL': 0.7999999999999998, 'BMI': 0.6}),
 7: AttributeValueSim(value=0.633982683982684, attributes={'AGE': 0.9, 'Urea': 0.6666666666666666, 'Cr': 0.9428571428571428, 'HbA1c': 0.0, 'Chol': 0.7333333333333331, 'TG': 0.20000000000000018, 'HDL': 0.6969696969696967, 'LDL': 1.0, 'VLDL': 0.3999999999999999, 'BMI': 0.8}),
 578: AttributeValueSim(value=0.5876969696969697, attributes={'AGE': 0.9, 'Urea': 0.8000000000000002, 'Cr': 0.0, 'HbA1c': 0.4800000000000001, 'Chol': 0.0, 'TG': 1.0, 'HDL': 0.6969696969696967, 'LDL': 0.0, 'VLDL': 1.0, 'BMI': 1.0}),
 330: AttributeValueSim(value=0.5824891774891775, attributes={'AGE': 0.85, 'Urea': 0.8666666666666666, 'Cr': 0.0, 'HbA1c': 0.0, 'Chol': 1.0, 'TG': 0.8000000000000003, 'HDL': 0.3939393939393941, 'LDL': 0.7142857142857144, 'VLDL': 0.8, 'BMI': 0.4}),
 337: AttributeValueSim(value=0.5824891774891775, attributes={'AGE': 0.85, 'Urea': 0.8666666666666666, 'Cr': 0.0, 'HbA1c': 0.0, 'Chol': 1.0, 'TG': 0.8000000000000003, 'HDL': 0.3939393939393941, 'LDL': 0.7142857142857144, 'VLDL': 0.8, 'BMI': 0.4}),
 32: AttributeValueSim(value=0.5779004329004329, attributes={'AGE': 0.95, 'Urea': 0.8000000000000002, 'Cr': 0.42857142857142855, 'HbA1c': 0.4, 'Chol': 0.8000000000000002, 'TG': 0.30000000000000027, 'HDL': 0.09090909090909081, 'LDL': 0.8095238095238098, 'VLDL': 0.3999999999999999, 'BMI': 0.8})}

In [96]:
## View the ranking of the similar cases
result.final_step.ranking

(97, 98, 100, 103, 87, 7, 578, 330, 337, 32)

In [98]:
# print the full data of the similar case form the casebase
result.final_step.casebase

{97: {'ID': 143,
  'No_Pation': 24019,
  'Gender': 'F',
  'AGE': 48,
  'Urea': 4.0,
  'Cr': 38,
  'HbA1c': 6.8,
  'Chol': 4.4,
  'TG': 2.3,
  'HDL': 1.3,
  'LDL': 2.2,
  'VLDL': 1.0,
  'BMI': 25.0,
  'CLASS': 'Y'},
 98: {'ID': 146,
  'No_Pation': 24020,
  'Gender': 'F',
  'AGE': 48,
  'Urea': 4.0,
  'Cr': 38,
  'HbA1c': 6.8,
  'Chol': 4.4,
  'TG': 2.3,
  'HDL': 1.3,
  'LDL': 2.2,
  'VLDL': 1.0,
  'BMI': 25.0,
  'CLASS': 'Y'},
 100: {'ID': 426,
  'No_Pation': 41044,
  'Gender': 'F',
  'AGE': 48,
  'Urea': 4.0,
  'Cr': 38,
  'HbA1c': 6.8,
  'Chol': 4.4,
  'TG': 2.3,
  'HDL': 1.3,
  'LDL': 2.2,
  'VLDL': 1.0,
  'BMI': 25.0,
  'CLASS': 'Y'},
 103: {'ID': 692,
  'No_Pation': 87662,
  'Gender': 'F',
  'AGE': 48,
  'Urea': 4.0,
  'Cr': 38,
  'HbA1c': 6.8,
  'Chol': 4.4,
  'TG': 2.3,
  'HDL': 1.3,
  'LDL': 2.2,
  'VLDL': 1.0,
  'BMI': 25.0,
  'CLASS': 'Y'},
 87: {'ID': 150,
  'No_Pation': 34287,
  'Gender': 'F',
  'AGE': 42,
  'Urea': 2.8,
  'Cr': 39,
  'HbA1c': 4.6,
  'Chol': 4.7,
  'TG': 2.5,
  'HDL': 1.3,
  'LDL': 2.4,
  'VLDL': 1.1,
  'BMI': 25.0,
  'CLASS': 'Y'},
 7: {'ID': 402,
  'No_Pation': 34235,
  'Gender': 'F',
  'AGE': 50,
  'Urea': 3.5,
  'Cr': 39,
  'HbA1c': 4.0,
  'Chol': 4.0,
  'TG': 1.5,
  'HDL': 1.2,
  'LDL': 2.2,
  'VLDL': 0.7,
  'BMI': 24.0,
  'CLASS': 'N'},
 578: {'ID': 130,
  'No_Pation': 45386,
  'Gender': 'F',
  'AGE': 50,
  'Urea': 4.3,
  'Cr': 61,
  'HbA1c': 7.8,
  'Chol': 6.2,
  'TG': 2.3,
  'HDL': 1.2,
  'LDL': 4.1,
  'VLDL': 1.0,
  'BMI': 23.0,
  'CLASS': 'Y'},
 330: {'ID': 550,
  'No_Pation': 123,
  'Gender': 'F',
  'AGE': 51,
  'Urea': 4.2,
  'Cr': 72,
  'HbA1c': 11.2,
  'Chol': 4.4,
  'TG': 2.1,
  'HDL': 1.1,
  'LDL': 2.5,
  'VLDL': 0.9,
  'BMI': 26.0,
  'CLASS': 'Y'},
 337: {'ID': 149,
  'No_Pation': 24021,
  'Gender': 'F',
  'AGE': 51,
  'Urea': 4.2,
  'Cr': 72,
  'HbA1c': 11.2,
  'Chol': 4.4,
  'TG': 2.1,
  'HDL': 1.1,
  'LDL': 2.5,
  'VLDL': 0.9,
  'BMI': 26.0,
  'CLASS': 'Y'},
 32: {'ID': 210,
  'No_Pation': 34257,
  'Gender': 'F',
  'AGE': 47,
  'Urea': 3.7,
  'Cr': 48,
  'HbA1c': 5.0,
  'Chol': 4.7,
  'TG': 1.6,
  'HDL': 1.0,
  'LDL': 2.4,
  'VLDL': 0.7,
  'BMI': 22.0,
  'CLASS': 'N'}}

In [102]:
result.default_query.similarities

{97: AttributeValueSim(value=0.948, attributes={'AGE': 1.0, 'Urea': 1.0, 'Cr': 1.0, 'HbA1c': 0.8800000000000001, 'Chol': 1.0, 'TG': 1.0, 'HDL': 1.0, 'LDL': 1.0, 'VLDL': 1.0, 'BMI': 0.6}),
 98: AttributeValueSim(value=0.948, attributes={'AGE': 1.0, 'Urea': 1.0, 'Cr': 1.0, 'HbA1c': 0.8800000000000001, 'Chol': 1.0, 'TG': 1.0, 'HDL': 1.0, 'LDL': 1.0, 'VLDL': 1.0, 'BMI': 0.6}),
 100: AttributeValueSim(value=0.948, attributes={'AGE': 1.0, 'Urea': 1.0, 'Cr': 1.0, 'HbA1c': 0.8800000000000001, 'Chol': 1.0, 'TG': 1.0, 'HDL': 1.0, 'LDL': 1.0, 'VLDL': 1.0, 'BMI': 0.6}),
 103: AttributeValueSim(value=0.948, attributes={'AGE': 1.0, 'Urea': 1.0, 'Cr': 1.0, 'HbA1c': 0.8800000000000001, 'Chol': 1.0, 'TG': 1.0, 'HDL': 1.0, 'LDL': 1.0, 'VLDL': 1.0, 'BMI': 0.6}),
 87: AttributeValueSim(value=0.6892380952380952, attributes={'AGE': 0.7, 'Urea': 0.19999999999999987, 'Cr': 0.9428571428571428, 'HbA1c': 0.23999999999999985, 'Chol': 0.8000000000000002, 'TG': 0.7999999999999998, 'HDL': 1.0, 'LDL': 0.8095238095238098, 'VLDL': 0.7999999999999998, 'BMI': 0.6}),
 7: AttributeValueSim(value=0.633982683982684, attributes={'AGE': 0.9, 'Urea': 0.6666666666666666, 'Cr': 0.9428571428571428, 'HbA1c': 0.0, 'Chol': 0.7333333333333331, 'TG': 0.20000000000000018, 'HDL': 0.6969696969696967, 'LDL': 1.0, 'VLDL': 0.3999999999999999, 'BMI': 0.8}),
 578: AttributeValueSim(value=0.5876969696969697, attributes={'AGE': 0.9, 'Urea': 0.8000000000000002, 'Cr': 0.0, 'HbA1c': 0.4800000000000001, 'Chol': 0.0, 'TG': 1.0, 'HDL': 0.6969696969696967, 'LDL': 0.0, 'VLDL': 1.0, 'BMI': 1.0}),
 330: AttributeValueSim(value=0.5824891774891775, attributes={'AGE': 0.85, 'Urea': 0.8666666666666666, 'Cr': 0.0, 'HbA1c': 0.0, 'Chol': 1.0, 'TG': 0.8000000000000003, 'HDL': 0.3939393939393941, 'LDL': 0.7142857142857144, 'VLDL': 0.8, 'BMI': 0.4}),
 337: AttributeValueSim(value=0.5824891774891775, attributes={'AGE': 0.85, 'Urea': 0.8666666666666666, 'Cr': 0.0, 'HbA1c': 0.0, 'Chol': 1.0, 'TG': 0.8000000000000003, 'HDL': 0.3939393939393941, 'LDL': 0.7142857142857144, 'VLDL': 0.8, 'BMI': 0.4}),
 32: AttributeValueSim(value=0.5779004329004329, attributes={'AGE': 0.95, 'Urea': 0.8000000000000002, 'Cr': 0.42857142857142855, 'HbA1c': 0.4, 'Chol': 0.8000000000000002, 'TG': 0.30000000000000027, 'HDL': 0.09090909090909081, 'LDL': 0.8095238095238098, 'VLDL': 0.3999999999999999, 'BMI': 0.8})}

In [ ]:
### Build a reuse function 

mac_reuse = cbrkit.reuse.build

In [281]:
mac_reuse = cbrkit.reuse.build(retriever_func = mac_sim  )
fac_reuse = cbrkit.reuse.build(fac_sim)
# mac_retriever = cbrkit.retrieval.dropout(
#     cbrkit.retrieval.build(mac_sim), 
#     min_similarity=1.0, 
#     limit = 400)
# fac_retriever = cbrkit.retrieval.dropout(
#     cbrkit.retrieval.build(fac_sim), 
#     limit=10)

result = cbrkit.reuse.apply_query(casebase, new_query, (mac_reuse, fac_reuse))

TypeError: build.__init__() missing 1 required positional argument: 'adaptation_func'

In [282]:
mac_reuse = cbrkit.reuse.build(
    retriever_func=cbrkit.retrieval.build(mac_sim),
    solution_attr="CLASS",
    aggregator="majority",
    k=5
)

fac_reuse = cbrkit.reuse.build(
    retriever_func=cbrkit.retrieval.build(fac_sim),
    solution_attr="CLASS",
    aggregator="majority",
    k=5
)

TypeError: build.__init__() got an unexpected keyword argument 'solution_attr'

In [252]:
def result_to_full_df(result, topk=None):
    # last retrieval step
    q = result.steps[-1].queries["default"]
    ranking = list(q.ranking)
    if topk:
        ranking = ranking[:topk]

    rows = []
    for cid in ranking:
        sim = q.similarities[cid]
        case = q.casebase[cid]   # this is the FULL original row you loaded
        row = {"case_id": cid, "similarity": float(sim.value)}
        row.update(case)         # merge all columns from the case
        rows.append(row)

    return pl.DataFrame(rows)

# Usage
df_full = result_to_full_df(result, topk=20)  # or topk=None for all
print(df_full)

shape: (10, 16)
┌─────────┬────────────┬─────┬───────────┬───┬─────┬──────┬──────┬───────┐
│ case_id ┆ similarity ┆ ID  ┆ No_Pation ┆ … ┆ LDL ┆ VLDL ┆ BMI  ┆ CLASS │
│ ---     ┆ ---        ┆ --- ┆ ---       ┆   ┆ --- ┆ ---  ┆ ---  ┆ ---   │
│ i64     ┆ f64        ┆ i64 ┆ i64       ┆   ┆ f64 ┆ f64  ┆ f64  ┆ str   │
╞═════════╪════════════╪═════╪═══════════╪═══╪═════╪══════╪══════╪═══════╡
│ 140     ┆ 1.0        ┆ 536 ┆ 34327     ┆ … ┆ 3.0 ┆ 0.7  ┆ 33.0 ┆ Y     │
│ 605     ┆ 1.0        ┆ 248 ┆ 24054     ┆ … ┆ 3.0 ┆ 0.7  ┆ 33.0 ┆ Y     │
│ 162     ┆ 0.671554   ┆ 317 ┆ 24077     ┆ … ┆ 2.1 ┆ 0.5  ┆ 33.0 ┆ Y     │
│ 168     ┆ 0.671554   ┆ 427 ┆ 34340     ┆ … ┆ 2.1 ┆ 0.5  ┆ 33.0 ┆ Y     │
│ 293     ┆ 0.666965   ┆ 480 ┆ 7687      ┆ … ┆ 3.2 ┆ 0.9  ┆ 33.0 ┆ Y     │
│ 231     ┆ 0.666537   ┆ 445 ┆ 34368     ┆ … ┆ 2.9 ┆ 0.7  ┆ 31.0 ┆ Y     │
│ 592     ┆ 0.651887   ┆ 176 ┆ 45445     ┆ … ┆ 1.8 ┆ 0.6  ┆ 30.0 ┆ Y     │
│ 525     ┆ 0.64968    ┆ 57  ┆ 6544      ┆ … ┆ 2.8 ┆ 0.7  ┆ 26.0 ┆ Y     │
│ 393     ┆ 0.634935   ┆ 531 ┆ 34496     ┆ … ┆ 3.1 ┆ 0.7  ┆ 33.0 ┆ Y     │
│ 385     ┆ 0.634156   ┆ 473 ┆ 34490     ┆ … ┆ 3.0 ┆ 0.6  ┆ 33.0 ┆ Y     │
└─────────┴────────────┴─────┴───────────┴───┴─────┴──────┴──────┴───────┘

In [273]:
# result.ranking
# result.similarities
result.casebase

{140: {'ID': 536,
  'No_Pation': 34327,
  'Gender': 'M',
  'AGE': 54,
  'Urea': 5.0,
  'Cr': 67,
  'HbA1c': 6.9,
  'Chol': 3.8,
  'TG': 1.7,
  'HDL': 1.1,
  'LDL': 3.0,
  'VLDL': 0.7,
  'BMI': 33.0,
  'CLASS': 'Y'},
 605: {'ID': 248,
  'No_Pation': 24054,
  'Gender': 'M',
  'AGE': 54,
  'Urea': 5.0,
  'Cr': 67,
  'HbA1c': 6.9,
  'Chol': 3.8,
  'TG': 1.7,
  'HDL': 1.1,
  'LDL': 3.0,
  'VLDL': 0.7,
  'BMI': 33.0,
  'CLASS': 'Y'},
 162: {'ID': 317,
  'No_Pation': 24077,
  'Gender': 'M',
  'AGE': 63,
  'Urea': 4.9,
  'Cr': 65,
  'HbA1c': 7.8,
  'Chol': 3.6,
  'TG': 1.1,
  'HDL': 1.0,
  'LDL': 2.1,
  'VLDL': 0.5,
  'BMI': 33.0,
  'CLASS': 'Y'},
 168: {'ID': 427,
  'No_Pation': 34340,
  'Gender': 'M',
  'AGE': 63,
  'Urea': 4.9,
  'Cr': 65,
  'HbA1c': 7.8,
  'Chol': 3.6,
  'TG': 1.1,
  'HDL': 1.0,
  'LDL': 2.1,
  'VLDL': 0.5,
  'BMI': 33.0,
  'CLASS': 'Y'},
 293: {'ID': 480,
  'No_Pation': 7687,
  'Gender': 'M',
  'AGE': 53,
  'Urea': 5.2,
  'Cr': 59,
  'HbA1c': 7.8,
  'Chol': 4.9,
  'TG': 2.1,
  'HDL': 0.9,
  'LDL': 3.2,
  'VLDL': 0.9,
  'BMI': 33.0,
  'CLASS': 'Y'},
 231: {'ID': 445,
  'No_Pation': 34368,
  'Gender': 'M',
  'AGE': 60,
  'Urea': 5.1,
  'Cr': 60,
  'HbA1c': 11.0,
  'Chol': 4.5,
  'TG': 1.7,
  'HDL': 0.9,
  'LDL': 2.9,
  'VLDL': 0.7,
  'BMI': 31.0,
  'CLASS': 'Y'},
 592: {'ID': 176,
  'No_Pation': 45445,
  'Gender': 'M',
  'AGE': 52,
  'Urea': 5.1,
  'Cr': 70,
  'HbA1c': 7.0,
  'Chol': 7.5,
  'TG': 1.7,
  'HDL': 1.2,
  'LDL': 1.8,
  'VLDL': 0.6,
  'BMI': 30.0,
  'CLASS': 'Y'},
 525: {'ID': 57,
  'No_Pation': 6544,
  'Gender': 'M',
  'AGE': 54,
  'Urea': 3.0,
  'Cr': 67,
  'HbA1c': 7.0,
  'Chol': 4.8,
  'TG': 1.7,
  'HDL': 1.3,
  'LDL': 2.8,
  'VLDL': 0.7,
  'BMI': 26.0,
  'CLASS': 'Y'},
 393: {'ID': 531,
  'No_Pation': 34496,
  'Gender': 'M',
  'AGE': 58,
  'Urea': 2.0,
  'Cr': 72,
  'HbA1c': 10.9,
  'Chol': 4.8,
  'TG': 1.6,
  'HDL': 1.0,
  'LDL': 3.1,
  'VLDL': 0.7,
  'BMI': 33.0,
  'CLASS': 'Y'},
 385: {'ID': 473,
  'No_Pation': 34490,
  'Gender': 'M',
  'AGE': 60,
  'Urea': 5.0,
  'Cr': 55,
  'HbA1c': 10.0,
  'Chol': 4.5,
  'TG': 1.3,
  'HDL': 0.9,
  'LDL': 3.0,
  'VLDL': 0.6,
  'BMI': 33.0,
  'CLASS': 'Y'}}

In [269]:
# Suppose `result` is your retrieval result

# Access the final step
final = result.final_step  # or result.steps[-1]

# See which case IDs were retrieved, in order
print("Ranking (top case IDs):", final.ranking)

# View similarities for those
print("Similarity values:")
for cid, sim in final.similarities.items():
    print(f"  ID={cid}, score={sim.value}")

# View the corresponding case data, including CLASS and other fields
print("Case data for retrieved cases:")
for cid, case in final.casebase.items():
    print(f"  ID={cid}, CLASS={case.get('CLASS')}, other fields...")

# And since `Result` has shortcuts, you can also directly do:
print(result.ranking)      # same as final.ranking
print(result.similarities) # final similarities
print(result.casebase)     # final casebase

Ranking (top case IDs): (140, 605, 162, 168, 293, 231, 592, 525, 393, 385)
Similarity values:
  ID=140, score=1.0
  ID=605, score=1.0
  ID=162, score=0.6715541125541126
  ID=168, score=0.6715541125541126
  ID=293, score=0.6669653679653679
  ID=231, score=0.6665367965367965
  ID=592, score=0.651887445887446
  ID=525, score=0.6496796536796536
  ID=393, score=0.6349350649350649
  ID=385, score=0.6341558441558441
Case data for retrieved cases:
  ID=140, CLASS=Y, other fields...
  ID=605, CLASS=Y, other fields...
  ID=162, CLASS=Y, other fields...
  ID=168, CLASS=Y, other fields...
  ID=293, CLASS=Y, other fields...
  ID=231, CLASS=Y, other fields...
  ID=592, CLASS=Y, other fields...
  ID=525, CLASS=Y, other fields...
  ID=393, CLASS=Y, other fields...
  ID=385, CLASS=Y, other fields...
(140, 605, 162, 168, 293, 231, 592, 525, 393, 385)
{140: AttributeValueSim(value=1.0, attributes={'AGE': 1.0, 'Urea': 1.0, 'Cr': 1.0, 'HbA1c': 1.0, 'Chol': 1.0, 'TG': 1.0, 'HDL': 1.0, 'LDL': 1.0, 'VLDL': 1.0, 'BMI': 1.0}), 605: AttributeValueSim(value=1.0, attributes={'AGE': 1.0, 'Urea': 1.0, 'Cr': 1.0, 'HbA1c': 1.0, 'Chol': 1.0, 'TG': 1.0, 'HDL': 1.0, 'LDL': 1.0, 'VLDL': 1.0, 'BMI': 1.0}), 162: AttributeValueSim(value=0.6715541125541126, attributes={'AGE': 0.55, 'Urea': 0.9333333333333336, 'Cr': 0.8857142857142857, 'HbA1c': 0.6400000000000002, 'Chol': 0.8666666666666668, 'TG': 0.40000000000000013, 'HDL': 0.6969696969696967, 'LDL': 0.142857142857143, 'VLDL': 0.6000000000000001, 'BMI': 1.0}), 168: AttributeValueSim(value=0.6715541125541126, attributes={'AGE': 0.55, 'Urea': 0.9333333333333336, 'Cr': 0.8857142857142857, 'HbA1c': 0.6400000000000002, 'Chol': 0.8666666666666668, 'TG': 0.40000000000000013, 'HDL': 0.6969696969696967, 'LDL': 0.142857142857143, 'VLDL': 0.6000000000000001, 'BMI': 1.0}), 293: AttributeValueSim(value=0.6669653679653679, attributes={'AGE': 0.95, 'Urea': 0.8666666666666666, 'Cr': 0.5428571428571428, 'HbA1c': 0.6400000000000002, 'Chol': 0.26666666666666633, 'TG': 0.5999999999999999, 'HDL': 0.39393939393939376, 'LDL': 0.8095238095238093, 'VLDL': 0.5999999999999999, 'BMI': 1.0}), 231: AttributeValueSim(value=0.6665367965367965, attributes={'AGE': 0.7, 'Urea': 0.9333333333333336, 'Cr': 0.6, 'HbA1c': 0.0, 'Chol': 0.5333333333333332, 'TG': 1.0, 'HDL': 0.39393939393939376, 'LDL': 0.9047619047619047, 'VLDL': 1.0, 'BMI': 0.6}), 592: AttributeValueSim(value=0.651887445887446, attributes={'AGE': 0.9, 'Urea': 0.9333333333333336, 'Cr': 0.8285714285714286, 'HbA1c': 0.9600000000000002, 'Chol': 0.0, 'TG': 1.0, 'HDL': 0.6969696969696973, 'LDL': 0.0, 'VLDL': 0.8, 'BMI': 0.4}), 525: AttributeValueSim(value=0.6496796536796536, attributes={'AGE': 1.0, 'Urea': 0.0, 'Cr': 1.0, 'HbA1c': 0.9600000000000002, 'Chol': 0.3333333333333333, 'TG': 1.0, 'HDL': 0.3939393939393941, 'LDL': 0.8095238095238093, 'VLDL': 1.0, 'BMI': 0.0}), 393: AttributeValueSim(value=0.6349350649350649, attributes={'AGE': 0.8, 'Urea': 0.0, 'Cr': 0.7142857142857143, 'HbA1c': 0.0, 'Chol': 0.3333333333333333, 'TG': 0.9000000000000001, 'HDL': 0.6969696969696967, 'LDL': 0.9047619047619047, 'VLDL': 1.0, 'BMI': 1.0}), 385: AttributeValueSim(value=0.6341558441558441, attributes={'AGE': 0.7, 'Urea': 1.0, 'Cr': 0.3142857142857143, 'HbA1c': 0.0, 'Chol': 0.5333333333333332, 'TG': 0.6000000000000001, 'HDL': 0.39393939393939376, 'LDL': 1.0, 'VLDL': 0.8, 'BMI': 1.0})}
{140: {'ID': 536, 'No_Pation': 34327, 'Gender': 'M', 'AGE': 54, 'Urea': 5.0, 'Cr': 67, 'HbA1c': 6.9, 'Chol': 3.8, 'TG': 1.7, 'HDL': 1.1, 'LDL': 3.0, 'VLDL': 0.7, 'BMI': 33.0, 'CLASS': 'Y'}, 605: {'ID': 248, 'No_Pation': 24054, 'Gender': 'M', 'AGE': 54, 'Urea': 5.0, 'Cr': 67, 'HbA1c': 6.9, 'Chol': 3.8, 'TG': 1.7, 'HDL': 1.1, 'LDL': 3.0, 'VLDL': 0.7, 'BMI': 33.0, 'CLASS': 'Y'}, 162: {'ID': 317, 'No_Pation': 24077, 'Gender': 'M', 'AGE': 63, 'Urea': 4.9, 'Cr': 65, 'HbA1c': 7.8, 'Chol': 3.6, 'TG': 1.1, 'HDL': 1.0, 'LDL': 2.1, 'VLDL': 0.5, 'BMI': 33.0, 'CLASS': 'Y'}, 168: {'ID': 427, 'No_Pation': 34340, 'Gender': 'M', 'AGE': 63, 'Urea': 4.9, 'Cr': 65, 'HbA1c': 7.8, 'Chol': 3.6, 'TG': 1.1, 'HDL': 1.0, 'LDL': 2.1, 'VLDL': 0.5, 'BMI': 33.0, 'CLASS': 'Y'}, 293: {'ID': 480, 'No_Pation': 7687, 'Gender': 'M', 'AGE': 53, 'Urea': 5.2, 'Cr': 59, 'HbA1c': 7.8, 'Chol': 4.9, 'TG': 2.1, 'HDL': 0.9, 'LDL': 3.2, 'VLDL': 0.9, 'BMI': 33.0, 'CLASS': 'Y'}, 231: {'ID': 445, 'No_Pation': 34368, 'Gender': 'M', 'AGE': 60, 'Urea': 5.1, 'Cr': 60, 'HbA1c': 11.0, 'Chol': 4.5, 'TG': 1.7, 'HDL': 0.9, 'LDL': 2.9, 'VLDL': 0.7, 'BMI': 31.0, 'CLASS': 'Y'}, 592: {'ID': 176, 'No_Pation': 45445, 'Gender': 'M', 'AGE': 52, 'Urea': 5.1, 'Cr': 70, 'HbA1c': 7.0, 'Chol': 7.5, 'TG': 1.7, 'HDL': 1.2, 'LDL': 1.8, 'VLDL': 0.6, 'BMI': 30.0, 'CLASS': 'Y'}, 525: {'ID': 57, 'No_Pation': 6544, 'Gender': 'M', 'AGE': 54, 'Urea': 3.0, 'Cr': 67, 'HbA1c': 7.0, 'Chol': 4.8, 'TG': 1.7, 'HDL': 1.3, 'LDL': 2.8, 'VLDL': 0.7, 'BMI': 26.0, 'CLASS': 'Y'}, 393: {'ID': 531, 'No_Pation': 34496, 'Gender': 'M', 'AGE': 58, 'Urea': 2.0, 'Cr': 72, 'HbA1c': 10.9, 'Chol': 4.8, 'TG': 1.6, 'HDL': 1.0, 'LDL': 3.1, 'VLDL': 0.7, 'BMI': 33.0, 'CLASS': 'Y'}, 385: {'ID': 473, 'No_Pation': 34490, 'Gender': 'M', 'AGE': 60, 'Urea': 5.0, 'Cr': 55, 'HbA1c': 10.0, 'Chol': 4.5, 'TG': 1.3, 'HDL': 0.9, 'LDL': 3.0, 'VLDL': 0.6, 'BMI': 33.0, 'CLASS': 'Y'}}

In [274]:
for cid in result.ranking[:5]:
    sim = result.similarities[cid].value
    case = result.casebase[cid]
    print(f"Case {cid}: CLASS={case['CLASS']}, similarity={sim:.3f}")

Case 140: CLASS=Y, similarity=1.000
Case 605: CLASS=Y, similarity=1.000
Case 162: CLASS=Y, similarity=0.672
Case 168: CLASS=Y, similarity=0.672
Case 293: CLASS=Y, similarity=0.667

In [277]:
mac_reuse = cbrkit.reuse.build(mac_sim)
fac_reuse = cbrkit.reuse.build(fac_sim)
# mac_retriever = cbrkit.retrieval.dropout(
#     cbrkit.retrieval.build(mac_sim), 
#     min_similarity=1.0, 
#     limit = 400)
# fac_retriever = cbrkit.retrieval.dropout(
#     cbrkit.retrieval.build(fac_sim), 
#     limit=10)

result = cbrkit.reuse.apply_query(casebase, new_query, (mac_reuse, fac_reuse))

TypeError: build.__init__() missing 1 required positional argument: 'retriever_func'